/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hard_Entity */

#ifndef _Included_com_hard_Entity
#define _Included_com_hard_Entity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hard_Entity
 * Method:    print1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hard_Entity_print1(JNIEnv *, jobject);

/*
 * Class:     com_hard_Entity
 * Method:    print2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hard_Entity_print2(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif